# Generated by Django 3.1.4 on 2021-02-12 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=50)),
                ('province', models.CharField(choices=[('QC', 'Quebec'), ('BC', 'British Columbia'), ('ON', 'Ontario'), ('AL', 'Alberta'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
