# Generated by Django 3.1.4 on 2021-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210212_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='answers',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
