# Generated by Django 3.1.4 on 2021-02-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questions', models.FileField(upload_to='')),
                ('answers', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(choices=[('AL', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan')], max_length=50),
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.resource')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.profile')),
            ],
        ),
    ]
