# Generated by Django 3.1.4 on 2021-02-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210213_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('12', '12'), ('undergraduate', 'undergraduate'), ('graduate', 'graduate')], max_length=50)),
                ('subject', models.CharField(choices=[('math', 'math'), ('algebra', 'algebra'), ('calculus', 'calculus'), ('algebra', 'algebra'), ('science', 'science'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('physics', 'physics'), ('history', 'history'), ('english', 'english'), ('french', 'french'), ('geography', 'geography')], max_length=50)),
            ],
        ),
    ]
